"""Constantes de dominio do backend de auditoria (vocabulario canonico).

Centraliza os valores de string que viajam por DB, IA, exports/BI e frontend:
status de auditoria, vereditos de contestacao, papeis de usuario, tipos de fonte
(audio/PDF), escopo de auditoria, status/prioridade da fila de revisao e o limiar
de aprovacao. Sao CONTRATOS — nao traduzir nem alterar os literais sem migracao
coordenada (DB grava esses textos crus e o frontend/BI os consome).

Pontos que confundem quem chega agora:
- `AUDIT_STATUS_CONTESTED` e um ALIAS de `AUDIT_STATUS_CONTESTATION_PENDING_REVIEW`
  (o status "contested" foi renomeado; `LEGACY_AUDIT_STATUS_CONTESTED='contested'`
  ainda existe para ler linhas antigas).
- `FECHAMENTO_NOTA_STATUSES`: quais status contam a nota na media do fechamento
  (toda auditoria salva conta, exceto descartada e contestacao aceita).
- `REVIEW_QUEUE_STATUS_ALL`/`READY_FOR_AUDIT` sao status "virtuais" de consulta
  (em `REVIEW_QUEUE_QUERY_STATUSES`), nao valores gravados na tabela.

Sem custo de API (so define constantes; nenhum acesso a banco/rede/CPU relevante).
"""
AUDIT_STATUS_AWAITING_PAIR = "awaiting_pair"
AUDIT_STATUS_PENDING_APPROVAL = "pending_approval"
AUDIT_STATUS_CONTESTATION_PENDING_REVIEW = "contestation_pending_review"
AUDIT_STATUS_APPROVED = "approved"
AUDIT_STATUS_CONTESTATION_ACCEPTED = "contestation_accepted"
AUDIT_STATUS_DISCARDED = "discarded"
LEGACY_AUDIT_STATUS_CONTESTED = "contested"
AUDIT_STATUS_CONTESTED = AUDIT_STATUS_CONTESTATION_PENDING_REVIEW
AUDIT_STATUSES = (
    AUDIT_STATUS_AWAITING_PAIR,
    AUDIT_STATUS_PENDING_APPROVAL,
    AUDIT_STATUS_CONTESTATION_PENDING_REVIEW,
    AUDIT_STATUS_APPROVED,
    AUDIT_STATUS_CONTESTATION_ACCEPTED,
    AUDIT_STATUS_DISCARDED,
)
DEFAULT_AUDIT_STATUS = AUDIT_STATUS_AWAITING_PAIR
LEGACY_AUDIT_STATUS_FALLBACK = AUDIT_STATUS_APPROVED

# Status que contam na media OPERACIONAL/TELEFONICA do fechamento: toda
# auditoria salva vale nota, exceto descartadas e contestacoes aceitas
# (o score deixa de valer). Antes so 'approved' contava e a nota "sumia"
# do fechamento enquanto o supervisor nao aprovava no portal.
FECHAMENTO_NOTA_STATUSES = (
    AUDIT_STATUS_AWAITING_PAIR,
    AUDIT_STATUS_PENDING_APPROVAL,
    AUDIT_STATUS_CONTESTATION_PENDING_REVIEW,
    AUDIT_STATUS_APPROVED,
    LEGACY_AUDIT_STATUS_CONTESTED,
)

AUDIT_CONTESTATION_VERDICT_ACCEPTED = "accepted"
AUDIT_CONTESTATION_VERDICT_REJECTED = "rejected"
AUDIT_CONTESTATION_VERDICTS = (
    AUDIT_CONTESTATION_VERDICT_ACCEPTED,
    AUDIT_CONTESTATION_VERDICT_REJECTED,
)

USER_ROLE_ADMIN = "admin"
USER_ROLE_SUPERVISOR = "supervisor"
USER_ROLES = (
    USER_ROLE_ADMIN,
    USER_ROLE_SUPERVISOR,
)
DEFAULT_USER_ROLE = USER_ROLE_ADMIN

SOURCE_TYPE_AUDIO = "audio"
SOURCE_TYPE_PDF = "pdf"
SOURCE_TYPES = (
    SOURCE_TYPE_AUDIO,
    SOURCE_TYPE_PDF,
)
DEFAULT_SOURCE_TYPE = SOURCE_TYPE_AUDIO

AUDIT_SCOPE_CALL_QUALITY = "call_quality"
AUDIT_SCOPES = (AUDIT_SCOPE_CALL_QUALITY,)
DEFAULT_AUDIT_SCOPE = AUDIT_SCOPE_CALL_QUALITY

REVIEW_QUEUE_STATUS_DOWNLOADED = "downloaded"
REVIEW_QUEUE_STATUS_PENDING = "pending"
REVIEW_QUEUE_STATUS_AUTO_RESOLVED = "auto_resolved"     
REVIEW_QUEUE_STATUS_REVIEWED = "reviewed"
REVIEW_QUEUE_STATUS_AUDITED = "audited"
REVIEW_QUEUE_STATUS_MONTHLY_CAPPED = "monthly_capped"   
REVIEW_QUEUE_STATUS_READY_FOR_AUDIT = "ready_for_audit" 
REVIEW_QUEUE_STATUS_NEEDS_MANUAL_TRIAGE = "needs_manual_triage"
REVIEW_QUEUE_STATUS_BLOCKED_OPERATOR = "blocked_operator"
REVIEW_QUEUE_STATUS_ALL = "all"
REVIEW_QUEUE_STATUSES = (
    REVIEW_QUEUE_STATUS_DOWNLOADED,
    REVIEW_QUEUE_STATUS_PENDING,
    REVIEW_QUEUE_STATUS_AUTO_RESOLVED,
    REVIEW_QUEUE_STATUS_REVIEWED,
    REVIEW_QUEUE_STATUS_AUDITED,
    REVIEW_QUEUE_STATUS_MONTHLY_CAPPED,
    REVIEW_QUEUE_STATUS_NEEDS_MANUAL_TRIAGE,
    REVIEW_QUEUE_STATUS_BLOCKED_OPERATOR,
)

REVIEW_QUEUE_READY_STATUSES = (
    REVIEW_QUEUE_STATUS_AUTO_RESOLVED,
    REVIEW_QUEUE_STATUS_REVIEWED,
)
REVIEW_QUEUE_MANUAL_TRIAGE_STATUSES = (
    REVIEW_QUEUE_STATUS_PENDING,
    REVIEW_QUEUE_STATUS_NEEDS_MANUAL_TRIAGE,
    REVIEW_QUEUE_STATUS_BLOCKED_OPERATOR,
)
REVIEW_QUEUE_QUERY_STATUSES = REVIEW_QUEUE_STATUSES + (
    REVIEW_QUEUE_STATUS_ALL,
    REVIEW_QUEUE_STATUS_READY_FOR_AUDIT,
)
DEFAULT_REVIEW_QUEUE_STATUS = REVIEW_QUEUE_STATUS_PENDING

REVIEW_QUEUE_PRIORITY_LOW = "low"
REVIEW_QUEUE_PRIORITY_MEDIUM = "medium"
REVIEW_QUEUE_PRIORITY_HIGH = "high"
REVIEW_QUEUE_PRIORITIES = (
    REVIEW_QUEUE_PRIORITY_LOW,
    REVIEW_QUEUE_PRIORITY_MEDIUM,
    REVIEW_QUEUE_PRIORITY_HIGH,
)
REVIEW_QUEUE_APPLICATION_DEFAULT_PRIORITY = REVIEW_QUEUE_PRIORITY_LOW
REVIEW_QUEUE_TABLE_DEFAULT_PRIORITY = REVIEW_QUEUE_PRIORITY_MEDIUM

AUDIT_PASS_THRESHOLD = 0.8
