from typing import Callable, Dict, List, Tuple
SPEAKER_OPERADOR = "Operador"
SPEAKER_MOTORISTA = "Motorista"
PERGUNTA_PREFIXOS = (
    "qual ",
    "quais ",
    "como ",
    "quando ",
    "onde ",
    "por que ",
    "porque ",
    "quem ",
    "que ",
    "pode ",
    "poderia ",
    "consegue ",
    "conseguiria ",
    "tem como ",
    "me fala",
    "me conta",
    "me diga",
    "me confirma",
    "me passa",
    "me informa",
    "confirma ",
)
OPERADOR_FRASES_SUPORTE = (
    "em que posso ajudar",
    "como posso ajudar",
    "so um momento",
    "vou verificar",
    "esta sendo solicitado",
    "pra gente",
    "diretamente aqui",
    "por e mail",
    "pode falar",
    "no assunto do e mail",
    "ficamos no aguardo",
    "caso ele nao traga",
    "vou pedir",
    "somos da opentech",
    "faz o rastreamento",
    "por nada",
    "eu gostaria de saber",
    "gostaria de saber referente",
    "falo com voce",
    # Logistics-specific support phrases
    "referente a posicao",
    "referente ao alerta",
    "referente a parada",
    "referente ao desvio",
    "referente a entrega",
    "referente a carga",
    "to ligando porque",
    "estou ligando porque",
    "ligo referente",
    "ligando referente",
    "o veiculo esta",
    "o caminhao esta",
    "nosso sistema mostra",
    "nosso sistema indica",
    "no sistema consta",
    "aparece aqui no sistema",
)
OPERADOR_FRASES_MUITO_FORTES = (
    "somos da opentech",
    "faz o rastreamento",
    "no assunto do e mail",
    "ficamos no aguardo",
    "caso ele nao traga",
    "vou pedir",
    "por nada",
    "bom dia opentech",
    "boa tarde opentech",
    "boa noite opentech",
    "central opentech",
    "central bas",
    "torre de controle",
)
OPERADOR_FRASES_POLICIA = (
    "em nome do rastreamento",
    "base de sinistro",
    "monitoracao de carga",
    "autocarga",
    "suspeita de sinistro",
    "botao de panico",
    "perdeu o sinal",
    "nao consegue mais contato com o motorista",
    "nao conseguimos mais contato com o motorista",
    "nao conseguiu contato mais com o condutor",
    "dados desse veiculo",
    "deixar os dados",
    "placa do cavalo",
    "cavalo mecanico",
    "expandindo as buscas",
    "expandindo nas buscas",
    "policias proximas",
    "contato para retorno",
)
OPERADOR_FRASES_INSTITUCIONAIS = (
    "nossos veiculos",
    "veiculo nosso",
    "nosso veiculo",
    "nao consigo contato com o motorista",
    "nao to conseguindo contato com o motorista",
    "nao estou conseguindo contato com motorista",
    "nao estou conseguindo contato com o motorista",
    "verificar pra mim",
    "verificar para mim",
    "a gente esta atuando",
    "a gente ta atuando",
    "estamos atuando",
    "modelo do veiculo",
    "atuando numa suspeita",
    "monitora o veiculo",
    "monitoracao de carga",
    "trabalha com monitoracao",
    "trabalha com rastreamento",
    "gente que faz o rastreamento",
    "deixando os dados",
    "deixar o modelo",
    "nossa equipe chegou",
    "o codigo desse cliente",
    "divergencia de preco",
    "problema no sistema",
    "erro interno",
    "devolucao parcial",
    "devolucao total",
    # Logistics-specific operator phrases
    "acionamento de escolta",
    "acionamento de prf",
    "gerenciadora de risco",
    "gerenciamento de risco",
    "posicao em atraso",
    "sem posicao",
    "perda de sinal",
    "sem sinal",
    "ultimo posicionamento",
    "ultima posicao",
    "esta parado desde",
    "parado ha",
    "parado a mais de",
    "qual o motivo da parada",
    "qual a previsao",
    "previsao de descarga",
    "previsao de entrega",
    "previsao de chegada",
    "qual a situacao",
    "como esta a situacao",
    "a gente precisa",
    "preciso que voce",
    "preciso de uma posicao",
    "nos informe",
    "nos de um retorno",
    "retomar a viagem",
    "retornar para a rota",
    "seguir viagem",
    "continuar a viagem",
    "plano de viagem",
    "instrucoes de rastreamento",
    "risco operacional",
    "risco do seguro",
    "vou registrar",
    "vou anotar",
    "fica registrado",
    "vou encaminhar",
    "vou informar ao cliente",
    "vou repassar",
    "estou entrando em contato",
    "ligo da opentech",
    "ligo da central",
    "estou ligando referente",
    "ligacao referente",
    "controle de temperatura",
    "desligamento de temperatura",
    "temperatura do bau",
)
RESPOSTAS_CURTAS_OPERADOR = ("pode", "sim", "nao", "claro", "perfeito", "certo", "isso")
RESPOSTAS_ACK_INTERLOCUTOR = ("brigada", "obrigada", "valeu", "ta bom", "tudo bem")
RESPOSTAS_CURTAS_INTERLOCUTOR = (
    "pode deixar",
    "consegue sim",
    "sim, pode",
    "pode sim",
    "com prf",
    "com delegado",
    "com sargento",
    "com tenente",
    "com capitao",
)
TELEPHONY_MARKERS_STRONG = (
    "digite",
    "opcao",
    "bem vindo",
    "fique na linha",
    "ligacao receptiva",
    "ligacao recebida",
    "sua ligacao e muito importante",
    "para outros motivos",
    "ura",
    "ivr",
)
TELEPHONY_MARKERS_SOFT = (
    "aguarde na linha",
    "torre mondelez",
    "para ser atendido",
    "atencao",
    "tecle",
    "se voce esta",
)
SUPPORT_POINT_HANDOFF_MARKERS = (
    "vou chamar",
    "deixa eu chamar",
    "vou verificar",
    "deixa eu verificar",
    "o motorista esta aqui",
    "ele esta aqui",
    "passar pro motorista",
    "passo pro motorista",
    "pera ai",
    "perai",
    "so um momento",
    "um momento que eu vou chamar",
    "aguenta ai",
)
LlmSpeakerMapper = Callable[
    [List["RawPhrase"], List[int], Dict[int, "SpeakerStats"], Dict[int, Dict[str, object]], str, str],
    Tuple[Dict[int, str], Dict[int, float], Tuple[int, ...]],
]